# Generated by Django 4.2.11 on 2024-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpatialProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longitude",
                    models.CharField(max_length=128, verbose_name="longitude"),
                ),
                ("latitude", models.CharField(max_length=128, verbose_name="latitude")),
            ],
        ),
    ]
