# Generated by Django 4.2.11 on 2024-04-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0002_remove_projet_coordonnee"),
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialprojet",
            name="leprojet",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="projet.projet",
            ),
        ),
    ]
