# Generated by Django 4.2.11 on 2024-04-14 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("map", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.CharField(max_length=5000, verbose_name="contenu")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "commentateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartiPrenante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AUTORITE_CONTRACTANTE", "Autorite Contractante"),
                            ("MAITRE_D_OUVRAGE", "Maitre d'Ouvrage"),
                            ("CHEF_DU_MARCHE", "Chef du Marché"),
                            ("INGENIEUR_DU_MARCHE", "Ingenieur du marché"),
                            ("MAITRISE_D_OEUVRE", "Maitrise d'Oeuvre"),
                        ],
                        max_length=30,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "specifications",
                    models.CharField(
                        max_length=100, verbose_name="specifications du rôle"
                    ),
                ),
                (
                    "lepartiprenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("caption", models.CharField(blank=True, max_length=128)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=128, verbose_name="titre")),
                (
                    "description",
                    models.CharField(max_length=5000, verbose_name="description"),
                ),
                ("descrip_reduit", models.CharField(max_length=350)),
                (
                    "financement",
                    models.CharField(max_length=100, verbose_name="Financement"),
                ),
                (
                    "entreprise",
                    models.CharField(max_length=100, verbose_name="Entreprise"),
                ),
                (
                    "delais_execution",
                    models.CharField(max_length=50, verbose_name="Delais d'execution"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coordonnee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map.spatialprojet",
                    ),
                ),
                (
                    "lescommentaire",
                    models.ManyToManyField(
                        related_name="commentaires",
                        through="projet.Commentaire",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partiprenantes",
                    models.ManyToManyField(
                        related_name="parti_prenantes",
                        through="projet.PartiPrenante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projet.photo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="partiprenante",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projet.projet"
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="leprojet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projet.projet"
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="photo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="projet.photo"
            ),
        ),
    ]
