# Generated by Django 4.2.11 on 2024-04-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="projet", name="coordonnee",),
    ]
